apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "v8s-router.labels" . | nindent 4 }}
  name: {{ include "v8s-router.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "v8s-router.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "v8s-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}