apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "v8s-router.labels" . | nindent 4 }}
  name: {{ include "v8s-router.fullname" . }}-manager-role
rules:
- apiGroups:
  - router.v8s.cedio.dev
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - router.v8s.cedio.dev
  resources:
  - routes/status
  verbs:
  - get
  - patch
  - update
