apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "v8s-router.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
  name: {{ include "v8s-router.fullname" . }}-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/component: controller-manager
